export const logbook = [
  "Sri Lanka",
  "Ceylon",
  "Colombo",
  "Kandy",
  "Galle",
  "Sigiriya",
  "Anuradhapura",
  "Polonnaruwa",
  "Dambulla",
  "Ella",
  "Nuwara Eliya",
  "Yala National Park",
  "Udawalawe National Park",
  "Mirissa",
  "Unawatuna",
  "Bentota",
  "Trincomalee",
  "Jaffna",
  "Arugam Bay",
  "Hikkaduwa",
  "Pinnawala Elephant Orphanage",
  "Adam's Peak",
  "Horton Plains National Park",
  "Sinharaja Forest Reserve",
  "Tea Plantations",
  "Cultural Triangle",
  "Wildlife Safari",
  "Beaches",
  "Ayurveda",
  "Temples",
  "Heritage Sites",
  "Whale Watching",
  "Surfing",
  "Adventure Tourism",
  "Trekking",
  "Historical Sites",
  "Scenic Train Rides",
  "Wildlife Conservation",
  "Botanical Gardens",
  "Cultural Festivals",
  "Sri Lankan Cuisine",
  "Local Markets",
  "Traditional Arts",
  "Handicrafts",
  "Gemstone Mining",
  "Waterfalls",
  "Lakes",
  "Rivers",
  "Nature Reserves",
  "National Parks",
  "Bird Watching",
  "Sri Lankan Culture",
  "Local Villages",
  "Spiritual Retreats",
  "Yoga Retreats",
  "Historical Ruins",
  "Colonial Architecture",
  "Lighthouse Tours",
  "Fishing Villages",
  "Coconut Plantations",
  "Spice Gardens",
  "Eco Tourism",
  "Marine Life",
  "Tropical Paradise",
];
